CREATE TABLE Users (
	userId INT NOT NULL AUTO_INCREMENT,
	userName VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
	PRIMARY KEY (userId)
);

CREATE TABLE NFLplayerStat (
    rank INT NOT NULL AUTO_INCREMENT,
    playerName VARCHAR(50) NOT NULL,
    team VARCHAR(50) NOT NULL,
    COMP INT NOT NULL,
    ATT INT NOT NULL,
    PCT FLOAT NOT NULL,
    YDS INT NOT NULL,
    YDS_A FLOAT NOT NULL,
    LONGP INT NOT NULL,
    TD INT NOT NULL,
    INTT INT NOT NULL,
    SACK INT NOT NULL,
    RATE FLOAT NOT NULL,
    YDS_G INT NOT NULL,
    PRIMARY KEY (rank)
);
